[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6

build_flags = 
    -D ESP32a

; PRIMEIRO UPLOAD: Use USB
upload_protocol = esptool
upload_port = COM5        ; MUDE PARA A PORTA DO SEU ESP32
; monitor_port = COM5     ; mesma porta para monitor serial

; DEPOIS que o programa estiver rodando, você pode usar OTA:
; upload_protocol = espota
; upload_port = 192.168.4.1
; upload_flags = --auth=ota1234